// Generated by CoffeeScript 1.3.3
(function() {
  var Canvas0,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Canvas0 = (function(_super) {

    __extends(Canvas0, _super);

    function Canvas0() {
      return Canvas0.__super__.constructor.apply(this, arguments);
    }

    Canvas0.prototype.setup = function() {
      this.fillColor = "#202020";
      this.strokeColor = 'rgba(0, 0, 0, 0.15)';
      return this.backgroundColor = 'rgb(240, 240, 240)';
    };

    Canvas0.prototype.update = function() {};

    Canvas0.prototype.draw = function() {};

    return Canvas0;

  })(Canvas);

  this.Canvas0 = Canvas0;

}).call(this);
