// Generated by CoffeeScript 1.3.1
(function() {
  document.writeln('<script type="text/javascript" src="js/jquery.js"></script>');
  document.writeln('<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>');
  document.writeln('<script type="text/javascript" src="js/canvas.js"></script>');
  document.writeln('<script type="text/javascript" src="js/canvas1.js"></script>');
  document.writeln('<script type="text/javascript" src="js/main.js"></script>');
}).call(this);
